using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

namespace EulerProblemThree
{

    class Program
    {
        static public long LIMIT = 4000000;

        static void Main(string[] args)
        {
            int FirstNumber = 1;
            int SecondNumber = 2;
            long SumOfEvenTerms = 0;

            while(FirstNumber < LIMIT || SecondNumber< LIMIT)
            {
                if((SecondNumber%2)==0)
                    SumOfEvenTerms +=SecondNumber;
                int temp = SecondNumber;
                SecondNumber += FirstNumber;
                FirstNumber = temp;  
             }
            Console.WriteLine(SumOfEvenTerms.ToString());
            Console.ReadLine();
        }
    }
}
